public with sharing class NodeTypes {
    
    public static final String IF_NODE = 'if';

    public static final String FILTER = 'filter';

    public static final String SOQL_LOAD = 'soqlLoad';

    public static final String UNION = 'union';

    public static final String RECOMMENDATION_LIMIT = 'recommendationLimit';

    public static final String SORT_NODE = 'sort';

    public static final String EXTERNAL_CONNECTION = 'actionContext';
}
